### ISSUE TITLE
Cannot find module js-yaml.

### ISSUE THREAD

**Issue by john-michaelburke** [Logerfo/newline-action#57]
This is my .github/workflows/newline.yml
```
name: Final new line
on:
  pull_request:
    types: [synchronize, opened]
jobs:
  build:
    name: New line
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: Logerfo/newline-action@0.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

This is my .github/newline.yml
```
autoCommit: true
ignorePaths: ["src/a/b/**", "src/a/c/**"]
```

I seem to be hitting this error:
```
Run Logerfo/newline-action@0.0.3
  with:
    github-token: ***
    config-path: .github/newline.yml
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'js-yaml'
Require stack:
- /home/runner/work/_actions/Logerfo/newline-action/0.0.3/src/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/Logerfo/newline-action/0.0.3/src/main.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/Logerfo/newline-action/0.0.3/src/main.js'
  ]
}
```

**Comment by Logerfo** [comment]
Hmm that's weird. I think the runner should install every dependency listed on `package.json`. I don't know if this is happening to someone else. This is the only report and I'm currently not using the action myself. I honestly don't know what is happening and I'm afraid I won't have the time to look into it in the near future. Anyone should feel free to dive into it and I'll gladly accept a pull request that fix any issue if that's the case.

**Comment by xavipanda** [comment]
same here..

**Comment by rlorenzo** [comment]
I am also getting the same error. Here is my configs:

.github/workflows/check_newline.yml

```
name: Checks new line
on:
  pull_request:
    types: [synchronize, opened]
jobs:
  build:
    name: New line
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: Logerfo/newline-action@0.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/newline.yml
```

.github/newline.yml

```
autoCommit: false
```

Stacktrace:

```
Run Logerfo/newline-action@0.0.3
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'js-yaml'
Require stack:
- /home/runner/work/_actions/Logerfo/newline-action/0.0.3/src/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/Logerfo/newline-action/0.0.3/src/main.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/Logerfo/newline-action/0.0.3/src/main.js'
  ]
}
```

**Comment by shekharkhedekar** [comment]
Same error here

**Comment by Logerfo** [comment]
Possible workaround (I didn't test it): https://github.com/Polymer/tools/issues/2810#issuecomment-389216704

**Comment by rlorenzo** [comment]
I ended up using another Github action to check for new lines:

```
name: Checks new line
on: [push]

jobs:
  fend:
    name: Fend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: njgibbon/fend@main
```
